import React, { useRef, useEffect, useState } from "react";
import * as THREE from "three";
import { motion } from "framer-motion";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";
import { useNavigate } from "react-router-dom";
import {
  ArrowRight,
  Brain,
  Target,
  Globe,
  ChevronDown,
  Terminal,
  Award,
  Users,
} from "lucide-react";

export default function HomePage() {
  const navigate = useNavigate();
  const mountRef = useRef(null);
  const [isVisible, setIsVisible] = useState(false);

  // Scroll animation handler
  useEffect(() => {
    const handleScroll = () => {
      const currentScrollPos = window.pageYOffset;
      setIsVisible(currentScrollPos > 100);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const handleCheckUserSigIn = () => {
    const user = localStorage.getItem("token");
    if (user) {
      navigate("/quiz");
    } else {
      navigate("/signup");
    }
  };

  const features = [
    {
      icon: <Brain className="w-8 h-8" />,
      title: "AI-Powered Questions",
      description:
        "Experience dynamic quizzes generated by advanced AI algorithms.",
      color: "from-blue-500 to-blue-600",
    },
    {
      icon: <Target className="w-8 h-8" />,
      title: "Adaptive Learning",
      description: "Questions adapt to your skill level for optimal learning.",
      color: "from-purple-500 to-purple-600",
    },
    {
      icon: <Globe className="w-8 h-8" />,
      title: "Global Community",
      description: "Connect and compete with learners worldwide.",
      color: "from-green-500 to-green-600",
    },
  ];

  const stats = [
    {
      icon: <Users className="w-6 h-6" />,
      value: "10K+",
      label: "Active Users",
    },
    {
      icon: <Terminal className="w-6 h-6" />,
      value: "50K+",
      label: "Questions",
    },
    {
      icon: <Award className="w-6 h-6" />,
      value: "95%",
      label: "Success Rate",
    },
  ];

  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-b from-[#1a1f37] to-[#2c3250]">
      {/* Hero Section */}
      <header className="relative min-h-screen flex items-center">
        <div className="absolute inset-0 bg-[url('/path/to/pattern.png')] opacity-10" />

        <div className="container mx-auto px-6 py-24 relative z-10">
          <div className="flex flex-col md:flex-row items-center gap-12">
            <motion.div
              initial={{ opacity: 0, x: -50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
              className="flex-1 text-center md:text-left"
            >
              <h1 className="text-5xl md:text-7xl font-bold mb-6 text-white">
                Quiz Smarter with{" "}
                <span className="bg-gradient-to-r from-yellow-300 via-yellow-400 to-orange-400 text-transparent bg-clip-text">
                  BrainQuest
                </span>
              </h1>
              <p className="text-xl text-gray-300 mb-8 max-w-2xl">
                Embark on a journey of knowledge with AI-powered quizzes that
                adapt to your learning style and help you achieve mastery.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center md:justify-start">
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={handleCheckUserSigIn}
                  className="group flex items-center justify-center gap-2 bg-gradient-to-r from-yellow-400 to-orange-500 text-[#1a1f37] font-semibold px-8 py-4 rounded-full hover:shadow-lg hover:shadow-yellow-500/25 transition-all duration-300"
                >
                  Get Started
                  <ArrowRight className="group-hover:translate-x-1 transition-transform" />
                </motion.button>
                <a
                  href="#features"
                  className="flex items-center justify-center gap-2 text-gray-300 hover:text-white px-8 py-4 rounded-full border border-white/10 hover:border-white/20 transition-all duration-300"
                >
                  Learn More
                  <ChevronDown className="animate-bounce" />
                </a>
              </div>
            </motion.div>

            <div className="flex-1">
              <div
                ref={mountRef}
                className="w-full aspect-square max-w-2xl mx-auto"
              />
            </div>
          </div>
        </div>
      </header>

      {/* Features Section */}
      <section id="features" className="py-24 bg-white/5">
        <div className="container mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl font-bold text-white mb-4">
              Why Choose BrainQuest?
            </h2>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto">
              Experience the future of learning with our cutting-edge features
              designed to enhance your knowledge journey.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.2 }}
                className="p-8 rounded-2xl bg-white/10 backdrop-blur-xl border border-white/10 hover:border-white/20 transition-all duration-300"
              >
                <div
                  className={`w-16 h-16 mb-6 rounded-xl bg-gradient-to-r ${feature.color} flex items-center justify-center`}
                >
                  {feature.icon}
                </div>
                <h3 className="text-2xl font-semibold text-white mb-4">
                  {feature.title}
                </h3>
                <p className="text-gray-300">{feature.description}</p>
              </motion.div>
            ))}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {stats.map((stat, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.2 }}
                className="text-center p-8 rounded-2xl bg-white/5 border border-white/10"
              >
                <div className="w-12 h-12 rounded-full bg-white/10 flex items-center justify-center mx-auto mb-4 text-yellow-400">
                  {stat.icon}
                </div>
                <div className="text-3xl font-bold text-white mb-2">
                  {stat.value}
                </div>
                <div className="text-gray-400">{stat.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-[#1a1f37]/80 backdrop-blur-xl border-t border-white/10">
        <div className="container mx-auto px-6 py-12">
          <div className="flex flex-col md:flex-row justify-between items-center gap-8">
            <div className="text-center md:text-left">
              <h3 className="text-2xl font-bold bg-gradient-to-r from-yellow-300 to-orange-400 text-transparent bg-clip-text mb-2">
                BrainQuest
              </h3>
              <p className="text-gray-400">
                &copy; {new Date().getFullYear()} All rights reserved
              </p>
            </div>

            <div className="flex gap-6">
              {[
                { name: "Facebook", icon: "/icons/facebook.svg", url: "#" },
                { name: "Instagram", icon: "/icons/instagram.svg", url: "#" },
                { name: "LinkedIn", icon: "/icons/linkedin.svg", url: "#" },
              ].map((social, index) => (
                <motion.a
                  key={index}
                  href={social.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  whileHover={{ scale: 1.1 }}
                  whileTap={{ scale: 0.9 }}
                  className="w-10 h-10 rounded-full bg-white/10 p-2 hover:bg-white/20 transition-colors"
                >
                  <img
                    src={social.icon}
                    alt={social.name}
                    className="w-full h-full object-contain"
                  />
                </motion.a>
              ))}
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
